"""
emotes.py
=========
Loads the shared mood icons (generated by tools/generate_emotes.py) into
``QPixmap`` objects, keyed by name: happy, love, angry, sad, surprised, music,
bell.  Missing files are simply skipped so the pet still runs without them.
"""

from __future__ import annotations

import os

from PyQt5.QtGui import QPixmap


def load_emotes(assets_dir: str) -> dict[str, QPixmap]:
    emotes: dict[str, QPixmap] = {}
    folder = os.path.join(assets_dir, "emotes")
    if not os.path.isdir(folder):
        return emotes
    for name in os.listdir(folder):
        if name.lower().endswith(".png"):
            pix = QPixmap(os.path.join(folder, name))
            if not pix.isNull():
                emotes[os.path.splitext(name)[0]] = pix
    return emotes


# Modern dark stylesheet shared by every right-click / tray menu.
MENU_QSS = """
QMenu {
    background-color: #2b2d3a;
    color: #eef0fa;
    border: 1px solid #444862;
    border-radius: 10px;
    padding: 6px;
}
QMenu::item {
    padding: 7px 28px 7px 14px;
    border-radius: 7px;
    margin: 1px 4px;
    font-size: 12px;
}
QMenu::item:selected { background-color: #5a6cff; color: white; }
QMenu::item:disabled { color: #8a8da3; }
QMenu::separator { height: 1px; background: #444862; margin: 6px 12px; }
QMenu::indicator {
    width: 14px; height: 14px; margin-left: 6px;
}
QMenu::indicator:checked {
    background-color: #5a6cff; border-radius: 4px; border: 2px solid #2b2d3a;
}
QMenu::right-arrow { margin: 4px; }
"""
